encoding: utf-8
timezone: America/Los_Angeles

author: Samvel Khalatyan
title: C++11
description: Notes and Exercises for The C++ Programming Language 4th ed

baseurl: /cpp11
chapters: 44

category_list:
  - name: notes
    description: chapter notes
  - name: exercises
    description: exercises for chapters

include: ['_pages']

relative_permalinks: false
defaults:
  - scope:
        path: ""
        type: post
    values:
        layout: post

markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - strikethrough
    - superscript
    - tables
